const dashboardData = {
  "generatedAt": "2026-08-22T06:02:34.980Z",
  "leagueAvgGoalsPerTeam": 1.5,
  "playerStats": {},
  "standings": [],
  "upcoming": [
    {
      "externalId": "FI117220826",
      "startDate": "2026-08-22T06:05:00Z",
      "isCancelled": false,
      "teamAName": "ATLETICO DE MADRID",
      "teamBName": "LIVERPOOL",
      "participantAName": "HANDLER",
      "participantBName": "MATRIX",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 58.43139737396989,
      "ouEloOverOdds": 2.5,
      "ouEloUnderOdds": 1.35,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "HANDLER",
      "h2hEloProb": 61.50211044154453,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI118220826",
      "startDate": "2026-08-22T06:08:00Z",
      "isCancelled": false,
      "teamAName": "MANCHESTER CITY",
      "teamBName": "REAL MADRID",
      "participantAName": "LAVA",
      "participantBName": "DART",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.32854011094574,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "DART",
      "h2hPoissonProb": 56.33258196642418,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "LAVA",
      "h2hEloProb": 67.77405874537268,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI119220826",
      "startDate": "2026-08-22T06:12:00Z",
      "isCancelled": false,
      "teamAName": "SPAIN",
      "teamBName": "ENGLAND",
      "participantAName": "TUSK",
      "participantBName": "CRUSADER",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 60.69298701008522,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "CRUSADER",
      "h2hEloProb": 61.1686066173835,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI120220826",
      "startDate": "2026-08-22T06:16:00Z",
      "isCancelled": false,
      "teamAName": "SPURS",
      "teamBName": "ARSENAL",
      "participantAName": "ARCTIC",
      "participantBName": "ASSAULT",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 63.34125616681465,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "ASSAULT",
      "h2hPoissonProb": 59.422965591097345,
      "h2hPoissonHomeOdds": 2.5,
      "h2hPoissonAwayOdds": 1.5,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 61.93441656295546,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI121220826",
      "startDate": "2026-08-22T06:20:00Z",
      "isCancelled": false,
      "teamAName": "FC BARCELONA",
      "teamBName": "SSC NAPOLI",
      "participantAName": "ARCADIA",
      "participantBName": "EXECUTOR",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI122220826",
      "startDate": "2026-08-22T06:23:00Z",
      "isCancelled": false,
      "teamAName": "FC BAYERN MUNCHEN",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "CHAOS",
      "participantBName": "LAVA",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "LAVA",
      "h2hEloProb": 64.06217875363653,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI123220826",
      "startDate": "2026-08-22T06:27:00Z",
      "isCancelled": false,
      "teamAName": "PORTUGAL",
      "teamBName": "SPAIN",
      "participantAName": "MAGICIAN",
      "participantBName": "TUSK",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.56667284533105,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "MAGICIAN",
      "h2hEloProb": 61.624635816750974,
      "h2hEloHomeOdds": 1.4,
      "h2hEloAwayOdds": 2.6
    },
    {
      "externalId": "FI124220826",
      "startDate": "2026-08-22T06:31:00Z",
      "isCancelled": false,
      "teamAName": "NEWCASTLE UTD",
      "teamBName": "SPURS",
      "participantAName": "COSMOS",
      "participantBName": "ARCTIC",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI125220826",
      "startDate": "2026-08-22T06:35:00Z",
      "isCancelled": false,
      "teamAName": "LIVERPOOL",
      "teamBName": "FC BARCELONA",
      "participantAName": "MATRIX",
      "participantBName": "ARCADIA",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI126220826",
      "startDate": "2026-08-22T06:38:00Z",
      "isCancelled": false,
      "teamAName": "FC BAYERN MUNCHEN",
      "teamBName": "REAL MADRID",
      "participantAName": "CHAOS",
      "participantBName": "DART",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "DART",
      "h2hPoissonProb": 56.0772215346639,
      "h2hPoissonHomeOdds": 2.5,
      "h2hPoissonAwayOdds": 1.5,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI127220826",
      "startDate": "2026-08-22T06:42:00Z",
      "isCancelled": false,
      "teamAName": "ENGLAND",
      "teamBName": "FRANCE",
      "participantAName": "CRUSADER",
      "participantBName": "BLITZ",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI128220826",
      "startDate": "2026-08-22T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "ASTON VILLA",
      "participantAName": "ASSAULT",
      "participantBName": "VENUS",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 61.63587950073966,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 70.20305765047041,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI129220826",
      "startDate": "2026-08-22T06:50:00Z",
      "isCancelled": false,
      "teamAName": "SSC NAPOLI",
      "teamBName": "ATLETICO DE MADRID",
      "participantAName": "EXECUTOR",
      "participantBName": "HANDLER",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI130220826",
      "startDate": "2026-08-22T06:53:00Z",
      "isCancelled": false,
      "teamAName": "REAL MADRID",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "DART",
      "participantBName": "LAVA",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.32854011094574,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "DART",
      "h2hPoissonProb": 56.3325819664242,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "LAVA",
      "h2hEloProb": 67.77405874537268,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    }
  ],
  "h2hData": [],
  "otherH2hData": [],
  "totalsParlay": [
    {
      "externalId": "FI120220826",
      "startDate": "2026-08-22T06:16:00Z",
      "isCancelled": false,
      "teamAName": "SPURS",
      "teamBName": "ARSENAL",
      "participantAName": "ARCTIC",
      "participantBName": "ASSAULT",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 63.34125616681465,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "ASSAULT",
      "h2hPoissonProb": 59.422965591097345,
      "h2hPoissonHomeOdds": 2.5,
      "h2hPoissonAwayOdds": 1.5,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 61.93441656295546,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI128220826",
      "startDate": "2026-08-22T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "ASTON VILLA",
      "participantAName": "ASSAULT",
      "participantBName": "VENUS",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 61.63587950073966,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 70.20305765047041,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI119220826",
      "startDate": "2026-08-22T06:12:00Z",
      "isCancelled": false,
      "teamAName": "SPAIN",
      "teamBName": "ENGLAND",
      "participantAName": "TUSK",
      "participantBName": "CRUSADER",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 60.69298701008522,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "CRUSADER",
      "h2hEloProb": 61.1686066173835,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI123220826",
      "startDate": "2026-08-22T06:27:00Z",
      "isCancelled": false,
      "teamAName": "PORTUGAL",
      "teamBName": "SPAIN",
      "participantAName": "MAGICIAN",
      "participantBName": "TUSK",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.56667284533105,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "MAGICIAN",
      "h2hEloProb": 61.624635816750974,
      "h2hEloHomeOdds": 1.4,
      "h2hEloAwayOdds": 2.6
    }
  ],
  "winnerParlay": [
    {
      "externalId": "FI120220826",
      "startDate": "2026-08-22T06:16:00Z",
      "isCancelled": false,
      "teamAName": "SPURS",
      "teamBName": "ARSENAL",
      "participantAName": "ARCTIC",
      "participantBName": "ASSAULT",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 63.34125616681465,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "ASSAULT",
      "h2hPoissonProb": 59.422965591097345,
      "h2hPoissonHomeOdds": 2.5,
      "h2hPoissonAwayOdds": 1.5,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 61.93441656295546,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI130220826",
      "startDate": "2026-08-22T06:53:00Z",
      "isCancelled": false,
      "teamAName": "REAL MADRID",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "DART",
      "participantBName": "LAVA",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.32854011094574,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "DART",
      "h2hPoissonProb": 56.3325819664242,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "LAVA",
      "h2hEloProb": 67.77405874537268,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI118220826",
      "startDate": "2026-08-22T06:08:00Z",
      "isCancelled": false,
      "teamAName": "MANCHESTER CITY",
      "teamBName": "REAL MADRID",
      "participantAName": "LAVA",
      "participantBName": "DART",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.32854011094574,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": "DART",
      "h2hPoissonProb": 56.33258196642418,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "LAVA",
      "h2hEloProb": 67.77405874537268,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    }
  ],
  "extraModelPerformance": {
    "ouPoisson": {
      "bets": 930,
      "wins": 596,
      "wr": 64.08602150537635,
      "profit": -392,
      "cov": 6.994058810257952
    },
    "ouElo": {
      "bets": 5048,
      "wins": 3232,
      "wr": 64.02535657686212,
      "profit": -1820.75,
      "cov": 37.963450402346396
    },
    "h2hPoisson": {
      "bets": 3401,
      "wins": 2113,
      "wr": 62.12878565127904,
      "profit": 338.699999999999,
      "cov": 25.57719786417989
    },
    "h2hElo": {
      "bets": 3155,
      "wins": 1984,
      "wr": 62.884310618066564,
      "profit": 92.10000000000133,
      "cov": 23.727156501466496
    },
    "rotation": {
      "ouPoisson": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0,
        "over": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        },
        "under": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        }
      },
      "ouElo": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0,
        "over": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        },
        "under": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        }
      },
      "h2hPoisson": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0
      },
      "h2hElo": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0
      }
    },
    "segments": [
      {
        "label": "4pm – 8pm",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      },
      {
        "label": "8pm – 12am",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      },
      {
        "label": "12am – 4am",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      }
    ]
  },
  "backtestOutput": "🧪 Poisson/Elo Prediction Models — Live 45-Day Performance (All-Time)\n  OU·Poisson    Bets: 930 | 596W/334L | WR: 64.1% | Profit: $-392.00 | Coverage: 7.0%\n  OU·Elo        Bets: 5048 | 3232W/1816L | WR: 64.0% | Profit: $-1820.75 | Coverage: 38.0%\n  H2H·Poisson   Bets: 3401 | 2113W/1288L | WR: 62.1% | Profit: $338.70 | Coverage: 25.6%\n  H2H·Elo       Bets: 3155 | 1984W/1171L | WR: 62.9% | Profit: $92.10 | Coverage: 23.7%\n\n====================================\n📊 This Rotation\n  OU·Poisson    Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  OU·Elo        Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  H2H·Poisson   Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  H2H·Elo       Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n\n  Over 2.5  — Poisson: $0.00 | Elo: $0.00 | Total: $0.00\n  Under 2.5 — Poisson: $0.00 | Elo: $0.00 | Total: $0.00\n\n====================================\n📊 GRAND TOTAL (This Rotation)\nTotal Profit: $0.00"
};