const dashboardData = {
  "generatedAt": "2026-08-24T06:07:19.559Z",
  "leagueAvgGoalsPerTeam": 1.5,
  "playerStats": {},
  "standings": [],
  "upcoming": [
    {
      "externalId": "FI099240826",
      "startDate": "2026-08-24T06:08:00Z",
      "isCancelled": false,
      "teamAName": "REAL MADRID",
      "teamBName": "PARIS SG",
      "participantAName": "ZT",
      "participantBName": "HAVOC",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": "UNDER",
      "ouPoissonProb": 69.42049298204309,
      "ouPoissonOverOdds": 2.5,
      "ouPoissonUnderOdds": 1.35,
      "ouEloPick": "UNDER",
      "ouEloProb": 78.39242682205128,
      "ouEloOverOdds": 2.5,
      "ouEloUnderOdds": 1.35,
      "h2hPoissonPick": "HAVOC",
      "h2hPoissonProb": 52.71855793779932,
      "h2hPoissonHomeOdds": 2.7,
      "h2hPoissonAwayOdds": 1.3,
      "h2hEloPick": "HAVOC",
      "h2hEloProb": 69.85999159496049,
      "h2hEloHomeOdds": 2.7,
      "h2hEloAwayOdds": 1.3
    },
    {
      "externalId": "FI100240826",
      "startDate": "2026-08-24T06:12:00Z",
      "isCancelled": false,
      "teamAName": "FRANCE",
      "teamBName": "ENGLAND",
      "participantAName": "BULLFROG",
      "participantBName": "MJ",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI101240826",
      "startDate": "2026-08-24T06:16:00Z",
      "isCancelled": false,
      "teamAName": "SPURS",
      "teamBName": "ARSENAL",
      "participantAName": "PLUTO",
      "participantBName": "HORIZON",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 59.82563275664864,
      "ouEloOverOdds": 1.3,
      "ouEloUnderOdds": 2.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI102240826",
      "startDate": "2026-08-24T06:20:00Z",
      "isCancelled": false,
      "teamAName": "FC BARCELONA",
      "teamBName": "LIVERPOOL",
      "participantAName": "COSMOS",
      "participantBName": "VENUS",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "VENUS",
      "h2hPoissonProb": 51.150325406710806,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "VENUS",
      "h2hEloProb": 63.639351324379966,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI103240826",
      "startDate": "2026-08-24T06:23:00Z",
      "isCancelled": false,
      "teamAName": "FC BAYERN MUNCHEN",
      "teamBName": "REAL MADRID",
      "participantAName": "DEZZY",
      "participantBName": "ZT",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 67.9352778445458,
      "ouEloOverOdds": 2.6,
      "ouEloUnderOdds": 1.3,
      "h2hPoissonPick": "DEZZY",
      "h2hPoissonProb": 53.89725225007914,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 67.87842220936776,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    },
    {
      "externalId": "FI104240826",
      "startDate": "2026-08-24T06:27:00Z",
      "isCancelled": false,
      "teamAName": "PORTUGAL",
      "teamBName": "FRANCE",
      "participantAName": "DART",
      "participantBName": "BULLFROG",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI105240826",
      "startDate": "2026-08-24T06:31:00Z",
      "isCancelled": false,
      "teamAName": "ASTON VILLA",
      "teamBName": "SPURS",
      "participantAName": "PHENOM",
      "participantBName": "PLUTO",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI106240826",
      "startDate": "2026-08-24T06:35:00Z",
      "isCancelled": false,
      "teamAName": "SSC NAPOLI",
      "teamBName": "FC BARCELONA",
      "participantAName": "ASSAULT",
      "participantBName": "COSMOS",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "ASSAULT",
      "h2hPoissonProb": 58.17502137989305,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 75.11873850763732,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    },
    {
      "externalId": "FI107240826",
      "startDate": "2026-08-24T06:38:00Z",
      "isCancelled": false,
      "teamAName": "FC BAYERN MUNCHEN",
      "teamBName": "PARIS SG",
      "participantAName": "DEZZY",
      "participantBName": "HAVOC",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 67.91811103651041,
      "ouEloOverOdds": 2.5,
      "ouEloUnderOdds": 1.35,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI108240826",
      "startDate": "2026-08-24T06:42:00Z",
      "isCancelled": false,
      "teamAName": "PORTUGAL",
      "teamBName": "ENGLAND",
      "participantAName": "DART",
      "participantBName": "MJ",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI109240826",
      "startDate": "2026-08-24T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "NEWCASTLE UTD",
      "participantAName": "HORIZON",
      "participantBName": "PROPHET",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 69.36564633551342,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "HORIZON",
      "h2hPoissonProb": 54.20557872018302,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI110240826",
      "startDate": "2026-08-24T06:50:00Z",
      "isCancelled": false,
      "teamAName": "LIVERPOOL",
      "teamBName": "ATLETICO DE MADRID",
      "participantAName": "VENUS",
      "participantBName": "ALIBI",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 63.899542454324795,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": "VENUS",
      "h2hPoissonProb": 54.10602386275642,
      "h2hPoissonHomeOdds": 2.6,
      "h2hPoissonAwayOdds": 1.4,
      "h2hEloPick": "ALIBI",
      "h2hEloProb": 61.28156860852343,
      "h2hEloHomeOdds": 2.6,
      "h2hEloAwayOdds": 1.4
    },
    {
      "externalId": "FI111240826",
      "startDate": "2026-08-24T06:53:00Z",
      "isCancelled": false,
      "teamAName": "PARIS SG",
      "teamBName": "REAL MADRID",
      "participantAName": "HAVOC",
      "participantBName": "ZT",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": "UNDER",
      "ouPoissonProb": 69.42049298204309,
      "ouPoissonOverOdds": 2.5,
      "ouPoissonUnderOdds": 1.35,
      "ouEloPick": "UNDER",
      "ouEloProb": 78.39242682205128,
      "ouEloOverOdds": 2.5,
      "ouEloUnderOdds": 1.35,
      "h2hPoissonPick": "HAVOC",
      "h2hPoissonProb": 52.71855793779932,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "HAVOC",
      "h2hEloProb": 69.85999159496049,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    },
    {
      "externalId": "FI112240826",
      "startDate": "2026-08-24T06:57:00Z",
      "isCancelled": false,
      "teamAName": "ENGLAND",
      "teamBName": "FRANCE",
      "participantAName": "MJ",
      "participantBName": "BULLFROG",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI113240826",
      "startDate": "2026-08-24T07:01:00Z",
      "isCancelled": false,
      "teamAName": "NEWCASTLE UTD",
      "teamBName": "SPURS",
      "participantAName": "PROPHET",
      "participantBName": "PLUTO",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 61.897484825138015,
      "ouEloOverOdds": 1.5,
      "ouEloUnderOdds": 2.3,
      "h2hPoissonPick": "PLUTO",
      "h2hPoissonProb": 53.448804480830994,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI114240826",
      "startDate": "2026-08-24T07:05:00Z",
      "isCancelled": false,
      "teamAName": "ATLETICO DE MADRID",
      "teamBName": "FC BARCELONA",
      "participantAName": "ALIBI",
      "participantBName": "COSMOS",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "ALIBI",
      "h2hEloProb": 73.47598898364626,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    }
  ],
  "h2hData": [],
  "otherH2hData": [],
  "totalsParlay": [
    {
      "externalId": "FI099240826",
      "startDate": "2026-08-24T06:08:00Z",
      "isCancelled": false,
      "teamAName": "REAL MADRID",
      "teamBName": "PARIS SG",
      "participantAName": "ZT",
      "participantBName": "HAVOC",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": "UNDER",
      "ouPoissonProb": 69.42049298204309,
      "ouPoissonOverOdds": 2.5,
      "ouPoissonUnderOdds": 1.35,
      "ouEloPick": "UNDER",
      "ouEloProb": 78.39242682205128,
      "ouEloOverOdds": 2.5,
      "ouEloUnderOdds": 1.35,
      "h2hPoissonPick": "HAVOC",
      "h2hPoissonProb": 52.71855793779932,
      "h2hPoissonHomeOdds": 2.7,
      "h2hPoissonAwayOdds": 1.3,
      "h2hEloPick": "HAVOC",
      "h2hEloProb": 69.85999159496049,
      "h2hEloHomeOdds": 2.7,
      "h2hEloAwayOdds": 1.3
    },
    {
      "externalId": "FI111240826",
      "startDate": "2026-08-24T06:53:00Z",
      "isCancelled": false,
      "teamAName": "PARIS SG",
      "teamBName": "REAL MADRID",
      "participantAName": "HAVOC",
      "participantBName": "ZT",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": "UNDER",
      "ouPoissonProb": 69.42049298204309,
      "ouPoissonOverOdds": 2.5,
      "ouPoissonUnderOdds": 1.35,
      "ouEloPick": "UNDER",
      "ouEloProb": 78.39242682205128,
      "ouEloOverOdds": 2.5,
      "ouEloUnderOdds": 1.35,
      "h2hPoissonPick": "HAVOC",
      "h2hPoissonProb": 52.71855793779932,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "HAVOC",
      "h2hEloProb": 69.85999159496049,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    },
    {
      "externalId": "FI109240826",
      "startDate": "2026-08-24T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "NEWCASTLE UTD",
      "participantAName": "HORIZON",
      "participantBName": "PROPHET",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 69.36564633551342,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "HORIZON",
      "h2hPoissonProb": 54.20557872018302,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI103240826",
      "startDate": "2026-08-24T06:23:00Z",
      "isCancelled": false,
      "teamAName": "FC BAYERN MUNCHEN",
      "teamBName": "REAL MADRID",
      "participantAName": "DEZZY",
      "participantBName": "ZT",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 67.9352778445458,
      "ouEloOverOdds": 2.6,
      "ouEloUnderOdds": 1.3,
      "h2hPoissonPick": "DEZZY",
      "h2hPoissonProb": 53.89725225007914,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 67.87842220936776,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    }
  ],
  "winnerParlay": [
    {
      "externalId": "FI106240826",
      "startDate": "2026-08-24T06:35:00Z",
      "isCancelled": false,
      "teamAName": "SSC NAPOLI",
      "teamBName": "FC BARCELONA",
      "participantAName": "ASSAULT",
      "participantBName": "COSMOS",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "ASSAULT",
      "h2hPoissonProb": 58.17502137989305,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "ASSAULT",
      "h2hEloProb": 75.11873850763732,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    },
    {
      "externalId": "FI109240826",
      "startDate": "2026-08-24T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "NEWCASTLE UTD",
      "participantAName": "HORIZON",
      "participantBName": "PROPHET",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 69.36564633551342,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "HORIZON",
      "h2hPoissonProb": 54.20557872018302,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI110240826",
      "startDate": "2026-08-24T06:50:00Z",
      "isCancelled": false,
      "teamAName": "LIVERPOOL",
      "teamBName": "ATLETICO DE MADRID",
      "participantAName": "VENUS",
      "participantBName": "ALIBI",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 63.899542454324795,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": "VENUS",
      "h2hPoissonProb": 54.10602386275642,
      "h2hPoissonHomeOdds": 2.6,
      "h2hPoissonAwayOdds": 1.4,
      "h2hEloPick": "ALIBI",
      "h2hEloProb": 61.28156860852343,
      "h2hEloHomeOdds": 2.6,
      "h2hEloAwayOdds": 1.4
    }
  ],
  "extraModelPerformance": {
    "ouPoisson": {
      "bets": 950,
      "wins": 606,
      "wr": 63.78947368421053,
      "profit": -415,
      "cov": 6.7658998646820026
    },
    "ouElo": {
      "bets": 5322,
      "wins": 3391,
      "wr": 63.716647876738065,
      "profit": -2032,
      "cov": 37.90328324193433
    },
    "h2hPoisson": {
      "bets": 3595,
      "wins": 2244,
      "wr": 62.42002781641168,
      "profit": 397.599999999998,
      "cov": 25.603589487928208
    },
    "h2hElo": {
      "bets": 3413,
      "wins": 2161,
      "wr": 63.31673014942866,
      "profit": 182.45000000000164,
      "cov": 24.30738551385229
    },
    "rotation": {
      "ouPoisson": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0,
        "over": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        },
        "under": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        }
      },
      "ouElo": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0,
        "over": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        },
        "under": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        }
      },
      "h2hPoisson": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0
      },
      "h2hElo": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0
      }
    },
    "segments": [
      {
        "label": "4pm – 8pm",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      },
      {
        "label": "8pm – 12am",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      },
      {
        "label": "12am – 4am",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      }
    ]
  },
  "backtestOutput": "🧪 Poisson/Elo Prediction Models — Live 45-Day Performance (All-Time)\n  OU·Poisson    Bets: 950 | 606W/344L | WR: 63.8% | Profit: $-415.00 | Coverage: 6.8%\n  OU·Elo        Bets: 5322 | 3391W/1931L | WR: 63.7% | Profit: $-2032.00 | Coverage: 37.9%\n  H2H·Poisson   Bets: 3595 | 2244W/1351L | WR: 62.4% | Profit: $397.60 | Coverage: 25.6%\n  H2H·Elo       Bets: 3413 | 2161W/1252L | WR: 63.3% | Profit: $182.45 | Coverage: 24.3%\n\n====================================\n📊 This Rotation\n  OU·Poisson    Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  OU·Elo        Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  H2H·Poisson   Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  H2H·Elo       Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n\n  Over 2.5  — Poisson: $0.00 | Elo: $0.00 | Total: $0.00\n  Under 2.5 — Poisson: $0.00 | Elo: $0.00 | Total: $0.00\n\n====================================\n📊 GRAND TOTAL (This Rotation)\nTotal Profit: $0.00"
};