const dashboardData = {
  "generatedAt": "2026-09-22T06:07:39.266Z",
  "leagueAvgGoalsPerTeam": 1.5,
  "playerStats": {},
  "standings": [],
  "upcoming": [
    {
      "externalId": "FI113220926",
      "startDate": "2026-09-22T06:08:00Z",
      "isCancelled": false,
      "teamAName": "MANCHESTER CITY",
      "teamBName": "FC BAYERN MUNCHEN",
      "participantAName": "DEZZY",
      "participantBName": "GUARDIAN",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 66.11656040488195,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI114220926",
      "startDate": "2026-09-22T06:12:00Z",
      "isCancelled": false,
      "teamAName": "SPAIN",
      "teamBName": "FRANCE",
      "participantAName": "CHAOS",
      "participantBName": "DART",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DART",
      "h2hEloProb": 65.1130135112554,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI115220926",
      "startDate": "2026-09-22T06:16:00Z",
      "isCancelled": false,
      "teamAName": "SPURS",
      "teamBName": "ARSENAL",
      "participantAName": "ASSAULT",
      "participantBName": "PLUTO",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI116220926",
      "startDate": "2026-09-22T06:20:00Z",
      "isCancelled": false,
      "teamAName": "SSC NAPOLI",
      "teamBName": "FC BARCELONA",
      "participantAName": "CLINICAL",
      "participantBName": "SMHAMILA",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI117220926",
      "startDate": "2026-09-22T06:23:00Z",
      "isCancelled": false,
      "teamAName": "PARIS SG",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "FRANCHISE",
      "participantBName": "DEZZY",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 61.34647476729557,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": "FRANCHISE",
      "h2hPoissonProb": 52.82289211558656,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 62.60391030930676,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI118220926",
      "startDate": "2026-09-22T06:27:00Z",
      "isCancelled": false,
      "teamAName": "ENGLAND",
      "teamBName": "SPAIN",
      "participantAName": "SPARTAN",
      "participantBName": "CHAOS",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI119220926",
      "startDate": "2026-09-22T06:31:00Z",
      "isCancelled": false,
      "teamAName": "NEWCASTLE UTD",
      "teamBName": "SPURS",
      "participantAName": "COSMOS",
      "participantBName": "ASSAULT",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI120220926",
      "startDate": "2026-09-22T06:35:00Z",
      "isCancelled": false,
      "teamAName": "LIVERPOOL",
      "teamBName": "SSC NAPOLI",
      "participantAName": "RADICAL",
      "participantBName": "CLINICAL",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI121220926",
      "startDate": "2026-09-22T06:38:00Z",
      "isCancelled": false,
      "teamAName": "FC BAYERN MUNCHEN",
      "teamBName": "REAL MADRID",
      "participantAName": "GUARDIAN",
      "participantBName": "DEMOLISHOR",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI122220926",
      "startDate": "2026-09-22T06:42:00Z",
      "isCancelled": false,
      "teamAName": "FRANCE",
      "teamBName": "ENGLAND",
      "participantAName": "DART",
      "participantBName": "SPARTAN",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI123220926",
      "startDate": "2026-09-22T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "ASTON VILLA",
      "participantAName": "PLUTO",
      "participantBName": "VENUS",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "PLUTO",
      "h2hPoissonProb": 52.61682109377147,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "PLUTO",
      "h2hEloProb": 67.75391179804748,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    },
    {
      "externalId": "FI124220926",
      "startDate": "2026-09-22T06:50:00Z",
      "isCancelled": false,
      "teamAName": "LIVERPOOL",
      "teamBName": "FC BARCELONA",
      "participantAName": "RADICAL",
      "participantBName": "SMHAMILA",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 59.3076353929366,
      "ouEloOverOdds": 2.4,
      "ouEloUnderOdds": 1.4,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI125220926",
      "startDate": "2026-09-22T06:53:00Z",
      "isCancelled": false,
      "teamAName": "REAL MADRID",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "DEMOLISHOR",
      "participantBName": "DEZZY",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 56.55281546519619,
      "ouEloOverOdds": 2.4,
      "ouEloUnderOdds": 1.4,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 65.45197805886045,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    },
    {
      "externalId": "FI126220926",
      "startDate": "2026-09-22T06:57:00Z",
      "isCancelled": false,
      "teamAName": "FRANCE",
      "teamBName": "SPAIN",
      "participantAName": "DART",
      "participantBName": "CHAOS",
      "streamName": "Esoccer 2",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DART",
      "h2hEloProb": 65.1130135112554,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI127220926",
      "startDate": "2026-09-22T07:01:00Z",
      "isCancelled": false,
      "teamAName": "ASTON VILLA",
      "teamBName": "SPURS",
      "participantAName": "VENUS",
      "participantBName": "ASSAULT",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    }
  ],
  "h2hData": [],
  "otherH2hData": [],
  "totalsParlay": [
    {
      "externalId": "FI117220926",
      "startDate": "2026-09-22T06:23:00Z",
      "isCancelled": false,
      "teamAName": "PARIS SG",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "FRANCHISE",
      "participantBName": "DEZZY",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 61.34647476729557,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": "FRANCHISE",
      "h2hPoissonProb": 52.82289211558656,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 62.60391030930676,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI124220926",
      "startDate": "2026-09-22T06:50:00Z",
      "isCancelled": false,
      "teamAName": "LIVERPOOL",
      "teamBName": "FC BARCELONA",
      "participantAName": "RADICAL",
      "participantBName": "SMHAMILA",
      "streamName": "Esoccer 4",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 59.3076353929366,
      "ouEloOverOdds": 2.4,
      "ouEloUnderOdds": 1.4,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": null,
      "h2hEloProb": null,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI125220926",
      "startDate": "2026-09-22T06:53:00Z",
      "isCancelled": false,
      "teamAName": "REAL MADRID",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "DEMOLISHOR",
      "participantBName": "DEZZY",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "UNDER",
      "ouEloProb": 56.55281546519619,
      "ouEloOverOdds": 2.4,
      "ouEloUnderOdds": 1.4,
      "h2hPoissonPick": null,
      "h2hPoissonProb": null,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 65.45197805886045,
      "h2hEloHomeOdds": 2.5,
      "h2hEloAwayOdds": 1.5
    }
  ],
  "winnerParlay": [
    {
      "externalId": "FI117220926",
      "startDate": "2026-09-22T06:23:00Z",
      "isCancelled": false,
      "teamAName": "PARIS SG",
      "teamBName": "MANCHESTER CITY",
      "participantAName": "FRANCHISE",
      "participantBName": "DEZZY",
      "streamName": "Esoccer 1",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": "OVER",
      "ouEloProb": 61.34647476729557,
      "ouEloOverOdds": 1.4,
      "ouEloUnderOdds": 2.4,
      "h2hPoissonPick": "FRANCHISE",
      "h2hPoissonProb": 52.82289211558656,
      "h2hPoissonHomeOdds": 1.83,
      "h2hPoissonAwayOdds": 1.83,
      "h2hEloPick": "DEZZY",
      "h2hEloProb": 62.60391030930676,
      "h2hEloHomeOdds": 1.83,
      "h2hEloAwayOdds": 1.83
    },
    {
      "externalId": "FI123220926",
      "startDate": "2026-09-22T06:46:00Z",
      "isCancelled": false,
      "teamAName": "ARSENAL",
      "teamBName": "ASTON VILLA",
      "participantAName": "PLUTO",
      "participantBName": "VENUS",
      "streamName": "Esoccer 3",
      "tournamentName": "Esoccer H2H GG League",
      "matchStatus": null,
      "teamAScore": null,
      "teamBScore": null,
      "homeStyle": "Unknown",
      "awayStyle": "Unknown",
      "homeRecent": [],
      "awayRecent": [],
      "h2hFavored": "N/A",
      "h2hWinrate": 0,
      "h2hAvgGoals": 0,
      "h2hHistory": [],
      "h2hHistoryOU": [],
      "ouPoissonPick": null,
      "ouPoissonProb": null,
      "ouPoissonOverOdds": 1.6,
      "ouPoissonUnderOdds": 1.6,
      "ouEloPick": null,
      "ouEloProb": null,
      "ouEloOverOdds": 1.6,
      "ouEloUnderOdds": 1.6,
      "h2hPoissonPick": "PLUTO",
      "h2hPoissonProb": 52.61682109377147,
      "h2hPoissonHomeOdds": 1.3,
      "h2hPoissonAwayOdds": 2.7,
      "h2hEloPick": "PLUTO",
      "h2hEloProb": 67.75391179804748,
      "h2hEloHomeOdds": 1.3,
      "h2hEloAwayOdds": 2.7
    }
  ],
  "extraModelPerformance": {
    "ouPoisson": {
      "bets": 1103,
      "wins": 677,
      "wr": 61.37805983680871,
      "profit": -702,
      "cov": 6.648583484026522
    },
    "ouElo": {
      "bets": 6507,
      "wins": 4180,
      "wr": 64.23851237129246,
      "profit": -2284,
      "cov": 39.22242314647378
    },
    "h2hPoisson": {
      "bets": 3995,
      "wins": 2383,
      "wr": 59.64956195244056,
      "profit": -398.0000000000009,
      "cov": 24.080771549125977
    },
    "h2hElo": {
      "bets": 3680,
      "wins": 2247,
      "wr": 61.059782608695656,
      "profit": -304.3499999999981,
      "cov": 22.18203737191079
    },
    "rotation": {
      "ouPoisson": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0,
        "over": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        },
        "under": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        }
      },
      "ouElo": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0,
        "over": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        },
        "under": {
          "bets": 0,
          "wins": 0,
          "wr": 0,
          "profit": 0,
          "cov": 0
        }
      },
      "h2hPoisson": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0
      },
      "h2hElo": {
        "bets": 0,
        "wins": 0,
        "wr": 0,
        "profit": 0,
        "cov": 0
      }
    },
    "segments": [
      {
        "label": "4pm – 8pm",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      },
      {
        "label": "8pm – 12am",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      },
      {
        "label": "12am – 4am",
        "h2hPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "h2hElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouPoisson": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        },
        "ouElo": {
          "profit": 0,
          "bets": 0,
          "wr": 0
        }
      }
    ]
  },
  "backtestOutput": "🧪 Poisson/Elo Prediction Models — Live 45-Day Performance (All-Time)\n  OU·Poisson    Bets: 1103 | 677W/426L | WR: 61.4% | Profit: $-702.00 | Coverage: 6.6%\n  OU·Elo        Bets: 6507 | 4180W/2327L | WR: 64.2% | Profit: $-2284.00 | Coverage: 39.2%\n  H2H·Poisson   Bets: 3995 | 2383W/1612L | WR: 59.6% | Profit: $-398.00 | Coverage: 24.1%\n  H2H·Elo       Bets: 3680 | 2247W/1433L | WR: 61.1% | Profit: $-304.35 | Coverage: 22.2%\n\n====================================\n📊 This Rotation\n  OU·Poisson    Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  OU·Elo        Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  H2H·Poisson   Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n  H2H·Elo       Bets: 0 | 0W/0L | WR: 0.0% | Profit: $0.00 | Coverage: 0.0%\n\n  Over 2.5  — Poisson: $0.00 | Elo: $0.00 | Total: $0.00\n  Under 2.5 — Poisson: $0.00 | Elo: $0.00 | Total: $0.00\n\n====================================\n📊 GRAND TOTAL (This Rotation)\nTotal Profit: $0.00"
};